FORMAT: 1A
HOST: http://gorhino.apiblueprint.org/

# Gorhino API

Gorhino is an API to 

## Aookucatuibs Collection [/applications]

### List All applications [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Cron Service?",
                "creation_date": "2017-05-05T08:40:51.620Z",
                "created_by":"ivan.corrales.solera@gmail.com",
                "last_modification_date": "2017-08-05T08:40:51.620Z",
                "updated_by":"developer@wesovilabs.com",
            }
        ]

### Create a New Application [POST]

You may create a new application using this action. It takes a JSON
object containing an application and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "name": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }