FORMAT: 1A
HOST: http://gorhino.apiblueprint.org/

# Gorhino API

Gorhino is an API to 

## Applications Collection [/applications]

### List All applications [GET]
+ Request

    + Headers
        Location: /applications
        X-Auth: Token
    
+ Response 200 (application/json)
    
    + Attributes
        + id (string) - Application identifier
        + name (string) - Application name
        + description (string) - Application description
        
    
    + Body

        [
            {
                "id":"GHRKNZ",
                "name": "Gherkinize",
                "description":"",
                "creation_date": "2017-05-05T08:40:51.620Z",
                "created_by":"ivan.corrales.solera@gmail.com",
                "last_modification_date": "2017-08-05T08:40:51.620Z",
                "updated_by":"developer@wesovilabs.com",
                "_links": {
                    "self": {
                        "href":"http://gorhino.apiblueprint.org/applications/GHRKNZ"
                    },
                    "versions": {
                        "href":"http://gorhino.apiblueprint.org/applications/GHRKNZ/versions"
                    }
                }
            },
            {
                "id":"XKRPN",
                "name": "Exkorpion",
                "description":"",
                "creation_date": "2017-05-05T08:40:51.620Z",
                "created_by":"ivan.corrales.solera@gmail.com",
                "last_modification_date": "2017-08-05T08:40:51.620Z",
                "updated_by":"developer@wesovilabs.com",
                "_links": {
                    "self": {
                        "href":"http://gorhino.apiblueprint.org/applications/XKRPN"
                    },
                    "versions": {
                        "href":"http://gorhino.apiblueprint.org/applications/XKRPN/versions"
                    }
                }
            },
            
        ]

+ Response 409 (application/json)
    
    + Attributes
        + code (string) - Application name
        + description (string) - Application description
        
    
    + Body

            {
                "code":"ERR0213123",
                "description": "Gherkinize",
            }
        
### Create a New Application [POST]

You may create a new application using this action. It takes a JSON
object containing an application and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "name": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }